/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./components/BreadCrumb/index.vue')['default']
    CronTab: typeof import('./components/CronTab/index.vue')['default']
    CronTabDay: typeof import('./components/CronTab/components/CronTabDay.vue')['default']
    CronTabHour: typeof import('./components/CronTab/components/CronTabHour.vue')['default']
    CronTabMin: typeof import('./components/CronTab/components/CronTabMin.vue')['default']
    CronTabMonth: typeof import('./components/CronTab/components/CronTabMonth.vue')['default']
    CronTabSecond: typeof import('./components/CronTab/components/CronTabSecond.vue')['default']
    CronTabWeek: typeof import('./components/CronTab/components/CronTabWeek.vue')['default']
    CronTabYear: typeof import('./components/CronTab/components/CronTabYear.vue')['default']
    CrudTable: typeof import('./components/CrudTable/index.vue')['default']
    DictTag: typeof import('./components/DictTag/index.vue')['default']
    IconSelect: typeof import('./components/IconSelect/index.vue')['default']
    IFrame: typeof import('./components/IFrame/index.vue')['default']
    InnerLink: typeof import('./components/InnerLink/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RichEdit: typeof import('./components/RichEdit/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagsBar: typeof import('./components/TagsBar/index.vue')['default']
  }
}
